### ISSUE TITLE
Is window.dispatchOverlayEvent still being used?

### ISSUE THREAD

**Issue by 8749236** [OverlayPlugin/OverlayPlugin#13]
I never found any code in Overlay Plugin invokes this callback, is this used currently? By whom?

**Comment by 8749236** [comment]
When "dispatchOVerlayEvent" was added in "86c704e399e5a8a1bbffe318dad8a47c107e2e84", it was not referenced back then either.

**Comment by valarnin** [comment]
I'm not seeing any actual invocation of that method on any github repo per: https://github.com/search?q=dispatchOverlayEvent&type=code

However, the underlying `processEvent` function is used internally as part of the websocket loop. Probably, the window binding can be removed?

**Comment by 8749236** [comment]
Thank you, also welcome back.

ngld ***@***.***>于2023年4月4日 周二上午8:47写道：
