### ISSUE TITLE
Trigg and MapEffect lines

### ISSUE THREAD

**Issue by MyTechnoHunter** [OverlayPlugin/OverlayPlugin#133]
getting reports of not seeing them for trigg.. dont have any idea why atm..

**Comment by quisquous** [comment]
I mentioned this on discord privately, but I think this is maybe a Ravahn question, in terms of if there's some better/different/Ravahn-provided way to inject log lines that will make it to the handler that trigg is using.

**Comment by Makar8000** [comment]
This was fixed on Triggernometry side & can be closed.
