### ISSUE TITLE
Opcodes in config don't update when `resources/opcodes.jsonc` is updated

### ISSUE THREAD

**Issue by Makar8000** [OverlayPlugin/OverlayPlugin#174]
Let's say that we are in a situation where we accidently merge the wrong opcode on a game update, and at the same time we never did an OP release since it's unnecessary for opcode updates.

1. User opens ACT. OverlayPlugin fetches the latest opcodes since the config doesn't have any for the latest game ver.
2. Incorrect opcode is saved to the user's config
3. We realize the incorrect opcode issue and fix it, then do a new OP release (or don't, doesn't matter)
4. `resources/opcodes.jsonc` might have the correct opcode, but user config still has the incorrect one. Since the game ver in the config is the latest one, OP will not try to re-fetch opcodes or check `resources/opcodes.jsonc`.
 
One solution could be to always check the local `resources/opcodes.jsonc` first, and if there's no opcode for the latest game ver, then check the user config. If there's no opcode for the user config, fetch it from github & save it to the user config. This way if we do make a mistake with the opcodes, a new OP release will resolve the issue. Alternatively, you could just always try to fetch it from github, but I don't like the idea of always making an external request due to load time.

**Comment by Makar8000** [comment]
https://github.com/OverlayPlugin/OverlayPlugin/blob/8e3774363890091ed2a23d917ace465ffbdd4884/OverlayPlugin.Core/Integration/OverlayPluginLogLines.cs#L196-L213

There is a comment here implying that a release will work, but from testing + reading the code, it'll only check the resources file if the opcode doesn't exist in the config.

**Comment by quisquous** [comment]
Hmm.  I thought I tested this but maybe something is incorrect.  It could be probably be more clear in the code, regardless.

My understanding is that the constructor loads the config opcodes and the file opcodes separately.  If the config opcodes are from a previous OP release, it clears them in the config and does not use them.  Then when an opcode is missing, it first tries to get them from the config (which is guaranteed to be newer than the OP release, based on clearing earlier) and if that's missing it falls back to the file, and if that's missing it tries to download newer ones.

The intention is as you state, that you should be able to release OP to fix any bad opcodes, and any OP release takes precedence over anything in the config downloaded before that.

**Comment by Makar8000** [comment]
Ah, I didn't realize the existence of `CachedOpcodeOverlayPluginVersion` when doing testing, so that is probably why I experienced this. 

I did another test, this time downgrading the cache'd OP version, and the correct opcode was used. Sorry about that!

**Comment by quisquous** [comment]
No worries at all! It's a good question, and the code is clearly not obvious what's going on.  If you see some way to make it more clear (maybe the version check needs to be in the constructor with a comment?), feel free to let me know so it's less confusing.
