### ISSUE TITLE
KR 6.40 can't get CurrentWorldID from  `callOverlayHandler::getCombatants`

### ISSUE THREAD

**Issue by wbz0100** [OverlayPlugin/OverlayPlugin#259]
getting combatant list and i need using player's currentworldid. but `(...).combatants`  object array doesn't have CurrentWorldID (same in customlogline 261 CombatantMemory `Add`)

**Comment by valarnin** [comment]
Do you have an example call to `getCombatants` and an example `261` line? Feel free to censor player ID and player name if you want.

I'm looking to confirm other values around `CurrentWorldID` appear to be correct.

**Comment by wbz0100** [comment]
```
0:
AggressionStatus: 0
BNpcID: 0
BNpcNameID: 0
CastBuffID: 0
CastDurationCurrent: 0
CastDurationMax: -36893490000000000000
CastTargetID: 0
CurrentCP: 0
CurrentGP: 0
CurrentHP: 103998
CurrentMP: 10000
CurrentWorldID: 0
Distance: null
EffectiveDistance: null
Effects: []
Heading: 1.56619883
ID: 0
IsCasting1: 0
IsCasting2: 0
IsTargetable: false
Job: 0
Level: 0
MaxCP: 0
MaxGP: 0
MaxHP: 103998
MaxMP: 10000
ModelStatus: 0
MonsterType: 0
NPCTargetID: 0
Name: ""
OwnerID: 0
PCTargetID: 2805477456
PartyType: 0
PosX: -8.965307
PosY: 114.056221
PosZ: 66.9548645
Radius: 1.61111116
Status: 0
TargetID: 2805477456
TransformationId: 0
Type: 1
WeaponId: 0
WorldID: 0
WorldName: null
```
`ffxiv_act_plugin v2.4.2.6`
call script: `(async () => { let combatants = (await callOverlayHandler({ call: 'getCombatants' })).combatants; for(let i in combatants) { combatants[i].Name = ''; combatants[i].ID = 0; } console.log(combatants); })();`

`261|2023-11-03T07:13:12.9307871+09:00|Add|{PlayerID}|CastDurationMax|-36893490000000000000.0000|CurrentMP|10000|Heading|3.1338|MaxHP|36732|MaxMP|10000|Name|{PlayerName}|NPCTargetID|86B321D0|PCTargetID|A739F7F0|PosX|-0.2833|PosY|-26.6464|PosZ|42.9991|Radius|0.5000|Type|1|35b3a70b5a8932ae`

**Comment by valarnin** [comment]
This looks like the normal expected Combatant struct change. #265 might fix this, but the built artifact will need to be manually installed to test.

If you're willing to test, you can find the built artifact at the bottom of the page here:

https://github.com/OverlayPlugin/OverlayPlugin/actions/runs/6738958353?pr=265

**Comment by wbz0100** [comment]
it's working on test build :p thx for maintaining!
