### ISSUE TITLE
Support building in Visual Studio

### ISSUE THREAD

**Issue by quisquous** [OverlayPlugin/OverlayPlugin#277]
It's a bit awkward to have to go run `build.bat` in order to be able to build from within Visual Studio.

At the very least, some sort of stopgap "hey you need to run this script once" more obvious error could make this less worse.

**Comment by valarnin** [comment]
I might look into this after the SDK project format PR is merged.

What are your thoughts on moving off of the python scripts for dependency fetching to something written entirely in powershell or as a C# application? It's a little difficult to write a pre-build step that can successfully invoke python and will work on anyone's machine.

**Comment by quisquous** [comment]
I think I'd be fine with that! We already have C# dependencies for the client structs, so one more seems fine.
