### ISSUE TITLE
RegisterProcessChangedHandler has initialization races

### ISSUE THREAD

**Issue by quisquous** [OverlayPlugin/OverlayPlugin#31]
See: https://github.com/OverlayPlugin/OverlayPlugin/pull/26#discussion_r950884430 and quisquous/cactbot#4093

It'd be nice if `RegisterProcessChangedHandler` always returned the existing process when registering for the first time.  If the process has already been set at the time of registration, then registering will miss that first call.

**Comment by valarnin** [comment]
There seems to be commented out code to handle this, I'm not sure why it's commented out.

https://github.com/OverlayPlugin/OverlayPlugin/blob/d239a8950640245810cce1ca14db79fd7d7bc0d7/OverlayPlugin.Core/Integration/FFXIVRepository.cs#L307-L322

**Comment by 8749236** [comment]
I'm working on a pull request that fix this issue.
This issue usually don't occur if plugin is already enabled, it only occurs if it loads before FFXIV_ACT_Plugin or gets enabled after ACT has started.

**Comment by 8749236** [comment]
Update: I had came up with a solution that fixes this issue without overhauling how it works, but still has race condition in it just a lot less likely to happen.
Gonna need bit more time on this.

**Comment by 8749236** [comment]
PR #48 has been created for this issue.

**Comment by 8749236** [comment]
This issue was supposedly fixed 5 days ago by [valarnin](https://github.com/OverlayPlugin/OverlayPlugin/commits?author=valarnin) in commit https://github.com/OverlayPlugin/OverlayPlugin/commit/5b117e31973a2e5b7253088f57a75863c0a87f4a.
However the change is undocumented in the commit, please test it yourself.

**Comment by quisquous** [comment]
Yeah, it looks like this was fixed.
