### ISSUE TITLE
Request to read combatants from memory directly

### ISSUE THREAD

**Issue by tssailzz8** [OverlayPlugin/OverlayPlugin#33]
~~i thinks we can read all the combants like Dalamud instead of read FFXIV_ACT_Plugin,beacuse in DSR p7 if we read the caster of StartsUsing '6D9C',we can figure out the safe the place that we do not need move.But in most if we use 'getCombatants' to get combatants we can not get complete.So i hope we can read all combants~~

------

Currently, OverlayPlugin gets the combatants data completely through FFXIV_ACT_Plugin. However, FFXIV_ACT_Plugin only reads the relative position and orientation of the specific entity when a part of the network packet is updated, which leads to the fact that the data we fetch from `getCombatants` function is often not up-to-date.For example Exaflare '6D9C' in DSR P7, if we read the caster of this skill through memory, then we can calculate the safe zone. Is it possible to let OverlayPlugin get these data through memory directly?
Modified by @ShadyWhite

**Comment by valarnin** [comment]
Here's a super hacky example of how this could work.

Problems:

1. Fields don't line up name-wise, I didn't bother checking actual value types but they might not line up either
2. As stated, this is really hacky and should be done better
3. It's ***extremely*** slow. Average time to complete the call handler is 1420ms, vs 3ms average against the FFXIV_ACT_Plugin method
4. Some properties are flat-out missing and would need to be mapped from memory

Unless the third and fourth problems can be resolved, this isn't really feasible.

Timing tested via opening devtools for an overlay and using this on console:

```js
ts=Date.now();await window.OverlayPluginApi.callHandler(JSON.stringify({'call':'getCombatants'}), (a)=>{console.log(JSON.parse(a));console.log(Date.now()-ts)});
```

https://gist.github.com/valarnin/b884a73b4cca5d7f10cb2797bace50c5

**Comment by valarnin** [comment]
Update: I fixed issue 3 here, there was just a problem with the logic I was using to avoid having to memscan again. It's still a tiny bit slower at 30ms but that's acceptable latency for this I think. At this point it's just a matter of tracking down if the missing info is available. This will require a separate function in `EnmityMemory##.cs` files though, since we don't want to filter this list down to just PC and Monster.

**Comment by xpdota** [comment]
Just in case, perhaps the best way to go about it would be to provide a new field(s) in the getCombatants WS request to customize the request, with the default behavior to emulate ACT's behavior. That way, things that aren't updated, nor things that simply aren't interested in the unfiltered version of combatants.

**Comment by tssailzz8** [comment]
i think we should only read objectid and pos,other is not important

**Comment by tssailzz8** [comment]
how do you change?

**Comment by valarnin** [comment]
`BNpcID` and `BNpcNameID` are both used in places. If this is going to replace existing functionality than at least those two will need to be mapped.
