### ISSUE TITLE
Duplicate key in opcodes.jsonc

### ISSUE THREAD

**Issue by Souma-Sumire** [OverlayPlugin/OverlayPlugin#335]
After #334, CN regions (6.51) and KR regions (6.50) now have the same key "2024.03.28.0000.0000"

**Comment by valarnin** [comment]
This will require restructuring the file or using a combined key, e.g. `$"{version}-${region}"`

The former would cause issues with existing versions if they do an online check for new opcodes.

The latter would cause additional CPU load to join strings, though maybe we can cache it?
