### ISSUE TITLE
Combatant data should be an array of objects

### ISSUE THREAD

**Issue by bsides** [OverlayPlugin/OverlayPlugin#338]
The original issue: https://github.com/ngld/OverlayPlugin/issues/204

I would like to make a request, to make the Combatant data an array of objects. Right now its data structure is not good, it's an object of keys, which are the player's name, in which we don't know anything about. It's not a searchable key because we don't know this data beforehand. To evaluate or manipulate this data in JavaScript, we are forced to convert it into an array of objects before doing anything and just ignoring its key completely (since there's a duplicated property `name`, which is good enough). By JSON standards, this would benefit a lot from being an array, one of the main benefits of it being a structure with a iterator.

What I'm asking is this, change from:

```json
Combatant: {
	"YOU": {
		// the combatant data
                // DPS: "100"
                // ENCDPS: "250"
                // name: "YOU"
                // ...etc
	},
	"Other Player": {
		// more combatant data
                // DPS: "100"
                // ENCDPS: "250"
                // name: "Other Player"
                // ...etc
	}
}
```

...to this:

```json
Combatants: [
	{
		// YOU combat data right here
                // DPS: "100"
                // ENCDPS: "250"
                // name: "YOU"
                // ...etc
	},
	{
		// OTHER PLAYER's combat data right here
                // DPS: "100"
                // ENCDPS: "250"
                // name: "Other Player"
                // ...etc
	}
]
```

This way, I would just iterate through Combatant (or other property name to make it retro compatible, like `Combatants` suggested above) and search whatever one would desire via modern JavaScript array methods like map, filter, reduce, find, toSorted, etc.

Would that be possible? Could I help with a PR?

Thank you in advance.

**Comment by valarnin** [comment]
This change would break every single DPS overlay, a number of which are no longer being actively updated/maintained, but are still in use by users.

Just going off of the built-in preset options, there are 10 overlays which would break.

**Comment by wexxlee** [comment]
> To evaluate or manipulate this data in JavaScript, we are forced to convert it into an array of objects before doing anything

I guess I'm also not clear on why something like `Object.values()` doesn't work for you?  It sounds like the combatant-name key data may be extraneous in your use case, but I don't know that's necessarily true for all other use cases.  For example, some use cases might involve capturing combatant name only, or might involve obtaining data for a specific/known combatant -- and in both those cases, iterating through an array is an added & unnecessary step.

**Comment by bsides** [comment]
I am the creator of Horizoverlay, and although it's not updated in ages, it still works. I should have started with that before, so here it is. Just FYI.

> This change would break every single DPS overlay, a number of which are no longer being actively updated/maintained, but are still in use by users.
> 
> Just going off of the built-in preset options, there are 10 overlays which would break.

As I mentioned earlier

> or other property name to make it retro compatible, like Combatants suggested above

It would not break if we did another property in the object, like `Combatants` (notice the ending S), and leaving the one that exist now untouched (Combatant). Could also be named something completely different (like Battlers), so developers wouldn't mistake both. Both would behave the exactly same, using the same functions just rendering a different JSON - Combatants unchanged, Combatants / Battlers an array of objects. I know, it's weird to duplicate the key, but it would make it backwards compatible.

> I guess I'm also not clear on why something like `Object.values()` doesn't work for you?

**Objects in JavaScript are not iterable**. That's my whole point. You need to iterate through every player, always, to make an Overlay. And then, you'd have to use a method to parse it, like `Object.values / .keys / .entries`, making that parse through javascript instead of receiving it easily through the Overlay plugin binary.

I mean, shouldn't we receive a data that is iterable in the first place? Why are we parsing it in the client?

I understand `Object` static methods works but they require a lot more to just work. It's not a good way to architect this kind of data. In that thought, no object should have "named objects" inside for a web application. It's not just me saying, a quick search will show you more in depth what I mean.

> For example, some use cases might involve capturing combatant name only, or might involve obtaining data for a specific/known combatant

Could you please give me an example? It's not possible to get the player name without the user explicitly inserting via a form or something alike. And then, if the user don't type it right, there is no way to retrieve a list without transforming it back into an array... so we're always working backwards. Also, this is a very edgy case, something I don't think a developer would use - I don't remember using it in Horizoverlay, neither another overlay for that matter.

It looks like a simple change and one that could help.

**Comment by wexxlee** [comment]
> It would not break if we did another property in the object, like `Combatants` (notice the ending S), and leaving the one that exist now untouched (Combatant). Could also be named something completely different (like Battlers), so developers wouldn't mistake both. Both would behave the exactly same, using the same functions just rendering a different JSON - `Combatant` unchanged, Combatants / Battlers an array of objects. I know, it's weird to duplicate the key, but it would make it backwards compatible.

It's not really backwards compatibility - it's parallel compatibility.  As valarnin notes, there are a number of overlays no longer actively maintained that use and will continue to use the existing property.  Your proposed change will involve maintaining both properties indefinitely; the original will never be deprecated or removed.

There's also the resource costs of delivering entirely duplicative data, coupled with potential confusion over why these two properties co-exist, which will happen regardless of whether the names are similar or distinct.

> > I guess I'm also not clear on why something like `Object.values()` doesn't work for you?
> 
> **Objects in JavaScript are not iterable**. That's my whole point. You need to iterate through every player, always, to make an Overlay. And then, you'd have to use a method to parse it, like `Object.values / .keys / .entries`, making that parse through javascript instead of receiving it easily through the Overlay plugin binary. [...] I understand `Object` static methods works but they require a lot more to just work. 

I understood your point.  But I don't think it's accurate to contrast the current implementation as "parse through javascript" and your proposal as "receiving it easily through the Overlay plugin binary."  In both cases, the data is delivered in JSON via WS, and in both cases, it needs to be deserialized/parsed in JS (or something else).  I also don't understand what you mean by "require a lot more to just work."  Is there something more that's required under the current architecture than just an `Object.values()` static method call that your proposal would reduce or eliminate?

> It's not possible to get the player name without the user explicitly inserting via a form or something alike. And then, if the user don't type it right, there is no way to retrieve a list without transforming it back into an array... so we're always working backwards. Also, this is a very edgy case, something I don't think a developer would use - I don't remember using it in Horizoverlay, neither another overlay for that matter.

I think you may be viewing this from the perspective of DPS-meter overlays, which accept whatever allies are present in the `Combatant` data set and display their DPS data, and are otherwise agnostic to combatant names.  There are other, non-DPS meter overlays that consume `Combatant` data that do have knowledge of combatant names and utilize the data differently.

**Comment by bsides** [comment]
> It's not really backwards compatibility - it's parallel compatibility. As valarnin notes, there are a number of overlays no longer actively maintained that use and will continue to use the existing property. Your proposed change will involve maintaining both properties indefinitely; the original will never be deprecated or removed.

They are the same properties with a really tiny different output, one is a Dictionary and the other is a List. Everything should stay the same except for this output, that would never change.

> I understood your point. 

Thanks for stating that. I really thought I was a little alien for a minute. I mean, lists in any modern web development are delivered as an array of objects. Right? 

> But I don't think it's accurate to contrast the current implementation as "parse through javascript" and your proposal as "receiving it easily through the Overlay plugin binary." In both cases, the data is delivered in JSON via WS, and in both cases, it needs to be deserialized/parsed in JS (or something else). 

Not really. To traverse through a dictionary (object) in javascript, you'd have to convert the data with a static method from Object (values, keys, entries...). To traverse through a list (array), since it's iterable, you have many other options without the need to convert it.

The point made is that the conversion done by the binary looks faster than done by the javascript, which is up there in the client, inside a browser window. And it's doing that each second (or whatever is the Overlay's tick).

> I also don't understand what you mean by "require a lot more to just work." Is there something more that's required under the current architecture than just an `Object.values()` static method call that your proposal would reduce or eliminate?

If the data came straight from the Overlay plugin as an array of objects, no one would have the need to convert it before using. Conversion meaning using Object static methods. If it was an iterable, you just... well, iterate and use the tools for iterables. That's the only intent. My proposal removes this step. I think you understood it before and I'm not trying to be condescending, just really trying to be clear.

> I think you may be viewing this from the perspective of DPS-meter overlays, which accept whatever allies are present in the `Combatant` data set and display their DPS data, and are otherwise agnostic to combatant names. There are other, non-DPS meter overlays that consume `Combatant` data that do have knowledge of combatant names and utilize the data differently.

You are totally right, I'm only seeing this as a DPS-meter overlay and I forgot about the other possibilities an overlay can do. My apologies for that. Maybe that's not feasible after all.

> There are other, non-DPS meter overlays that consume `Combatant` data that do have knowledge of combatant names and utilize the data differently.

You can't traverse a dictionary because it's not iterable, so that's not true. To have no knowledge of a player's name and still use the data, the developer needs to convert it into an array of objects beforehand. Of course, that's not the case for the actual player, which is always 'YOU' for whatever reason. 

I pretty much doubt any overlay using the dictionary as "combatant[name]" straight from the raw JSON without having to convert it.

I understand the resistance to make this any priority, the frontend can just deal and be done with it. It doesn't mean it's good though. Regardless, I appreciate the time and the discussion. Thank you.
