### ISSUE TITLE
Feature Request: New Catagories for ActorControlExtra Log Lines

### ISSUE THREAD

**Issue by MnFeN** [OverlayPlugin/OverlayPlugin#339]
OverlayPlugin recently added the `0x111` ActorControlExtra log lines, and there are currently 2 categories enabled.

Based on this, I would like to suggest adding the following categories besides #276:

- `0x0031 (49)`: Seems to be related with WeaponId, like in TOP P2/P5 M/F transformation  
  It would be much better if some useful categories could have their own log lines with fixed format (instead of only having the huge amount of `0x105` log lines for the triggers to match).  
    
- `0x0197 (407)`: Not sure about its meaning, but it contains useful data in raids.  
  _e.g._ whether the 8 summoned angels before Palladion are light/dark (P12s).  
  The log lines might look like: `111|...|4000ABCD|0197|0|11D3/11D4` for light/dark adds  
  These data are currently not available in other log lines.  
  
- `0x019d (413)`: EObjAnimation (according to [FFXIV-Packet-Dissector](https://github.com/zhyupe/FFXIV-Packet-Dissector/tree/320976363017b4a454c173e6f770af07dcf72608)).
  
Also, I am wondering if there could be some extra type of log lines with fixed format like `AddCombatant 03` , but contains the entity data in `105:Add:...`.  

Thank you!

**Comment by valarnin** [comment]
There's additional information and discussion about ActorControl categories in #276, for cross-reference.

Realistically, we could move `ActorControl`/`ActorControlTarget`/`ActorControlSelf` category additions to their own meta-issue instead.

To consider a category effectively, we need to know what the volume of the packets containing the category are, to assess for potential lag issues. So that would be something like `{X}% of ActorControl{Y} packets across all content types are of this category, and they're generally {spread out|come in bursts of Z packets|correspond to specific mechanics|etc}`.

It's important to consider the potential impact that adding new categories may have on lag when doing e.g. Alliance content, or Eureka NMs/Bozja CEs/Fates with a lot of enemies, or Baldesian Arsenal where there may be 56 players active in the same area, or world fates that may have 200+ players active in the same area.

---

> Also, I am wondering if there could be some extra type of log lines with fixed format like `AddCombatant 03` , but contains the entity data in `105:Add:...`.

I would much rather map out actual spawn data from the `LineSpawnNpcExtra` line's corresponding packet, and add additional lines corresponding to `SpawnPlayer`, `SpawnBoss`, and `SpawnObject`, if needed.

**Comment by MnFeN** [comment]
> There's additional information and discussion about ActorControl categories in #276, for cross-reference.
> 
> Realistically, we could move `ActorControl`/`ActorControlTarget`/`ActorControlSelf` category additions to their own meta-issue instead.
> 
> To consider a category effectively, we need to know what the volume of the packets containing the category are, to assess for potential lag issues. So that would be something like `{X}% of ActorControl{Y} packets across all content types are of this category, and they're generally {spread out|come in bursts of Z packets|correspond to specific mechanics|etc}`.
> 
> It's important to consider the potential impact that adding new categories may have on lag when doing e.g. Alliance content, or Eureka NMs/Bozja CEs/Fates with a lot of enemies, or Baldesian Arsenal where there may be 56 players active in the same area, or world fates that may have 200+ players active in the same area.
> 
> > Also, I am wondering if there could be some extra type of log lines with fixed format like `AddCombatant 03` , but contains the entity data in `105:Add:...`.
> 
> I would much rather map out actual spawn data from the `LineSpawnNpcExtra` line's corresponding packet, and add additional lines corresponding to `SpawnPlayer`, `SpawnBoss`, and `SpawnObject`, if needed.

Thanks for your reply! Sorry for the late response.  

> Realistically, we could move ActorControl/ActorControlTarget/ActorControlSelf category additions to their own meta-issue instead. 

I agree and that is what I meant: adding the categories in `0x111` log lines.

I do not have tools for analyzing network data, but I was using a plugin which parses some of the additional ActorControl data. It contains the `49` and `407` types, and they were not generated frequently. It could be confirmed by your statistics in #276:   

|Count|Packet Type|Category|
|---|---|---|
|335|ActorControl|49|

while the two other types `407` `413` I mentioned were not found.  

Additionally, I want to ask about also adding the type of controlling the visibility of an entity during raids, so that the useful data in log line `0x105 LineCombatantMemory` would be mostly covered, but I am not sure if it is frequent enough to cause significant performance impact.  

If you have some time, could you please look into these categories further? Thank you for your insights.

**Comment by valarnin** [comment]
I am working on a PR for this but I'm still not sure what `49` actually corresponds to. The best example I have available in my logs is from `Asura`:

```
21|2024-01-17T17:34:22.2490000-05:00|400105FC|Asura|8C8F|Many Faces|400105FC|Asura|1B|8C8F8000|0|0|0|0|0|0|0|0|0|0|0|0|0|0|2645054|27021908|10000|10000|||99.99|99.99|0.00|3.14|2645054|27021908|10000|10000|||99.99|99.99|0.00|3.14|00002F01|0|1|d4df3f816addb500
00|2024-01-17T17:34:22.0000000-05:00|282B||Asura uses Many Faces.|5a5d6192273b9e70
4096|2024-01-17T17:34:23.2780000-05:00|ActorControl|400105FC|49|000000F8|00000000|00000000|00000000|00000000|5213b74a92dc12fa
4096|2024-01-17T17:34:23.2780000-05:00|ActorControl|400105FC|49|000000F8|00000000|00000000|00000000|00000000|431fe5e27ebd65fc
4096|2024-01-17T17:34:23.2780000-05:00|ActorControl|400105FC|49|000000FC|00000000|00000000|00000000|00000000|e958e996e6fe96b3
...
21|2024-01-17T17:34:39.6000000-05:00|400105FC|Asura|8CAE|Many Faces|400105FC|Asura|1B|8CAE8000|0|0|0|0|0|0|0|0|0|0|0|0|0|0|1822409|27021908|10000|10000|||99.99|99.99|0.00|3.14|1822409|27021908|10000|10000|||99.99|99.99|0.00|3.14|00002F68|0|1|aab301335f3ed1d2
00|2024-01-17T17:34:39.0000000-05:00|282B||Asura uses Many Faces.|e37f4baef46b65d8
4096|2024-01-17T17:34:40.6210000-05:00|ActorControl|400105FC|49|000000FD|00000000|00000000|00000000|00000000|e3b35e63cf300cf3
4096|2024-01-17T17:34:40.6210000-05:00|ActorControl|400105FC|49|000000FD|00000000|00000000|00000000|00000000|f9ce11554c68e65d
4096|2024-01-17T17:34:40.6210000-05:00|ActorControl|400105FC|49|000000F9|00000000|00000000|00000000|00000000|b51a51fb62fd07f3
4096|2024-01-17T17:34:40.6210000-05:00|ActorControl|400105FC|49|000000F9|00000000|00000000|00000000|00000000|b347bae421c135ab
```

I ***think*** this corresponds to VFX slots or something, but I have no good way to verify. I would prefer to know exactly what this corresponds to so that the enum value can be named properly now, rather than breaking things down the line when it's tracked down.

I have also seen this packet happening in:
- Barbariccia (normal and extreme)
- Rubicante (extreme, not sure on normal)
- UWU (during Ultima's awakening, ~4s before the `Woken` buff is applied)

I have never seen it in:
- Golbez (normal or extreme)
- UCOB
- TEA

It does not correspond to any of the mapped values on `CombatantMemory` that we currently have, e.g. `WeaponId`.

**Comment by wexxlee** [comment]
> I _**think**_ this corresponds to VFX slots or something, but I have no good way to verify. I would prefer to know exactly what this corresponds to so that the enum value can be named properly now, rather than breaking things down the line when it's tracked down.

I only had a few mins to look at this earlier, but I definitely think it's vfx-related and not weapon.  Based on the timing after the `Many Faces` cast in Asura, it might correspond to the glowing rings or the blue 'face' animation on the boss, or the blue/red semicircles on the ground.

**Comment by valarnin** [comment]
I think that it's the like tan orb effect that happens at the end of the `Many Faces` cast, and not the red/blue faces. The faces I think are tied to the actual `The Face of <X>` cast.

Screenshot from some random YT video of the VFX that I think it corresponds to:
![image](https://github.com/OverlayPlugin/OverlayPlugin/assets/6119598/37affd02-4998-40de-b830-dfecfbb521a8)

But that's a lot of "I think" and assumptions, and I'd rather get something more concrete to confirm.

**Comment by MnFeN** [comment]
> I think that it's the like tan orb effect that happens at the end of the `Many Faces` cast, and not the red/blue faces. The faces I think are tied to the actual `The Face of <X>` cast.
> 
> Screenshot from some random YT video of the VFX that I think it corresponds to: ![image](https://private-user-images.githubusercontent.com/6119598/338807685-37affd02-4998-40de-b830-dfecfbb521a8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxODQzOTMsIm5iZiI6MTcxODE4NDA5MywicGF0aCI6Ii82MTE5NTk4LzMzODgwNzY4NS0zN2FmZmQwMi00OTk4LTQwZGUtYjgzMC1kZmVjZmJiNTIxYTgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MTJUMDkyMTMzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Y2JhYTEzNTNlNmJmNjA5MTZhOTdlZjYwOWZhNmU1MTI0NjBhNzA4OTc4ZTk5OGZhOWJkYTBiMjE0NjVjMWViMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.mifrEh7if1MvyowUxvjHR-Kg2DrlkoHYasEf4jGZ1N4)
> 
> But that's a lot of "I think" and assumptions, and I'd rather get something more concrete to confirm.

Thanks for your work! I will also try to gather some information about this enum.

By the way, recently I found there are some mechanism that could only use EObjAnimation to solve, like the rotation marks on the orbs/plates of the 3rd boss in Sil'dihn Subterrane.
