### ISSUE TITLE
Minor UI element sizing issues when running in custom DPI scaling

### ISSUE THREAD

**Issue by EQAditu** [OverlayPlugin/OverlayPlugin#352]
I'm trying to make ACT behave better when using non-100% DPI scaling and I'm currently reviewing various plugins to see if there are any issues that could be fixed.  The main thing that I am seeing is the page selection on the left-side of the UI.  It seems to resist the size adjustments that Windows tries to apply automatically to all controls and fonts.

![image](https://github.com/OverlayPlugin/OverlayPlugin/assets/52854036/0449e0d0-2637-42c6-ba60-1981677b83d4) 
![image](https://github.com/OverlayPlugin/OverlayPlugin/assets/52854036/a06d85b5-6041-4e01-ad7d-26849efe7acf) 
![image](https://github.com/OverlayPlugin/OverlayPlugin/assets/52854036/19fccd21-301e-4ee7-bd5e-13085cc45dc9)

These screenshots were taken with the new version of ACT(that has better scaling), but the current version of ACT has OverlayPlugin's UI also behave this way.  The width of the outer control seems to be fixed and the height of each individual selector seems fixed as well.  Windows rescales the font size to how it thinks it should, but with that resizing... the text has trouble fitting.

My observations so far are that native controls placed in Visual Studio or even UserControls inserted programmatically will get rescaled properly by Windows.  However controls created and sized in C# code will be taken literally and Windows will not rescale them.  It might have to do with SuspendLayout and ResumeLayout that InitializeComponent uses that makes it work for Visual Studio.

I'll have to browse through the code here to know for sure, but my guess is that these page selection "buttons" are sized with C# code after initialization.  You don't necessarily have to convert them to UserControls since these are pretty simple looking controls... but you'll need a way to know what size to make them.  Unfortunately the Microsoft provided methods of detecting DPI are pretty useless and don't even agree with each other.  `Control.DeviceDpi` always said 100% and several pinvoke methods also failed to give a proper result.  I gave up before trying other methods that rely on later OS versions which would make ACT incompatible with older Windows OSes for no reason.  ACT *will have* a `FormActMain.DpiScale` property, but that won't help you right this second.  That was made with a hidden Panel that's just 96x96 and will get resized automatically by Windows.  You could do this as well to get the current DPI of your UI.

**Comment by valarnin** [comment]
The tabs on this page are a custom control defined in https://github.com/OverlayPlugin/OverlayPlugin/blob/a0fc018531ba129db8cb8dee4ed0f7c9bb871249/OverlayPlugin.Core/Controls/TabControlExt.cs

Any insight you can provide would be appreciated, as I don't really have any experience working with DPI scaling in C# or WinForms.

**Comment by EQAditu** [comment]
I will look at this later.  I was just trying to get the ball rolling with some background.

**Comment by EQAditu** [comment]
So, it looks like this is just an extended TabControl with some brute-force repainting.  In essense, the TabControl is set to show tabs on the left side instead of the top.  Normally Windows would draw this as a 90º turned tab, text and all.  Instead of pushing the TabPage down by the tab size, it pushes it right by that amount.  

The modifications here intercept all paint requests since, I guess, the userpaint method Microsoft gives wasn't good enough.  (I couldn't use it to theme TabControls either, so I understand)  Usually the paint message event specifies an area of the control to redraw... but this code ignores the clipping rectangle.  It asks the original TabControl to paint normally, then it wipes everything clear and redraws everything.  So instead of drawing one "tab" on-demand, it draws the entire collection and the background.  Switching tabs only invalidates the area of 3-4 tabs... so, this excessive painting isn't too bad.

I thought this would mean it's as simple as adjusting the GDI+ calls to use different numbers based on the scale, but the TabControl is doing funny things and not reporting the correct sizes at runtime.  So far, I'm running under the assumption that I will be able to use my new DpiScale property in ACT...  It would cause a MethodNotFound exception and fail to load the TabControl if the ACT version is too old.  Is this okay, or should I try getting the value by reflection and silently fail?

**Comment by EQAditu** [comment]
Setting the ItemSize *after* the constructor seems to work better as it gets reverted to 100% DPI values otherwise.

@valarnin BTW, how do you want this received?  Just a code file with the changes or a pull request from 19.29?  (I'm not sure that's doable)  I tried using the main branch, but the plugin seemed horribly broken compared to the 19.29 tag sources which just worked.

**Comment by valarnin** [comment]
Hmm, I haven't had any issues with current `main` personally. You could add a diff to this issue I guess, if you can't get `main` to work to verify the changes yourself.

**Comment by EQAditu** [comment]
So here's a before and after...
![image](https://github.com/user-attachments/assets/7c496085-80da-483e-b56c-3b508f0acc97) ![image](https://github.com/user-attachments/assets/69c8e63f-4f9b-49fa-a25f-451f29bd3a39)

I'll hold off on a PR until after this game/plugin update has settled.  As I mentioned before, this does require a newer version of ACT than the 4 year old one you're currently linking to.
