### ISSUE TITLE
RSV lines are not working correctly in R4S

### ISSUE THREAD

**Issue by Akurosia** [OverlayPlugin/OverlayPlugin#389]
As described i tried to get all rsv content for the fflogs plugin and realized, that there is no translations + for me it showed only the language field as de even when i joined the game with jp and fr language as well
```
262|2024-08-01T21:05:25.9130000+02:00|de|0000000F|_rsv_38043_-1_2_0_0_SE2DC5B04_EE2DC5B04||7dd6080466a86054
262|2024-08-01T21:05:25.9130000+02:00|de|00000012|_rsv_38342_-1_2_0_0_SE2DC5B04_EE2DC5B04||3521ed0f296b6250
262|2024-08-01T21:05:25.9130000+02:00|de|0000000C|_rsv_20033_-1_2_0_0_SE2DC5B04_EE2DC5B04||c2be4054a92fc920
262|2024-08-01T21:05:25.9130000+02:00|de|00000006|_rsv_20034_-1_2_0_0_SE2DC5B04_EE2DC5B04||832cc77b7de3c95d
262|2024-08-01T21:05:25.9130000+02:00|de|00000009|_rsv_37118_-1_2_0_0_SE2DC5B04_EE2DC5B04||dc205efcc3b06add
```

**Comment by Akurosia** [comment]
I could gather the debug log lines for English, French and German. Maybe this will help to get this fixed (can provide japanese on my next raid day)
[German Debug lines for RSV Data.log](https://github.com/user-attachments/files/16475602/German.Debug.lines.for.RSV.Data.log)
[English Debug lines for RSV Data.log](https://github.com/user-attachments/files/16475603/English.Debug.lines.for.RSV.Data.log)
[French Debug lines for RSV Data.log](https://github.com/user-attachments/files/16475604/French.Debug.lines.for.RSV.Data.log)

**Comment by valarnin** [comment]
This should fix it but I'm not in a position right now to test, if someone else wants to PR that's fine.
```cs
using System;
using System.Runtime.InteropServices;
using RainbowMage.OverlayPlugin.MemoryProcessors;
using RainbowMage.OverlayPlugin.NetworkProcessors.PacketHelper;

namespace RainbowMage.OverlayPlugin.NetworkProcessors
{
    class LineRSV : LineBaseCustom<
            Server_MessageHeader_Global, LineRSV.RSV_v62,
            Server_MessageHeader_CN, LineRSV.RSV_v62,
            Server_MessageHeader_KR, LineRSV.RSV_v62>
    {
        [StructLayout(LayoutKind.Explicit, Size = structSize, Pack = 1)]
        internal unsafe struct RSV_v62 : IPacketStruct
        {
            public const int structSize = 1080;
            public const int keySize = 0x64;
            public const int valueSize = 0x404;
            [FieldOffset(0x0)]
            public int valueByteCount;
            [FieldOffset(0x4)]
            public fixed byte key[keySize];
            [FieldOffset(0x68)]
            public fixed byte value[valueSize];

            public string ToString(long epoch, uint ActorID)
            {
                fixed (byte* key = this.key) fixed (byte* value = this.value)
                {
                    return
                        $"{ffxiv.GetLocaleString()}|" +
                        $"{valueByteCount:X8}|" +
                        $"{FFXIVMemory.GetStringFromBytes(key, keySize).Replace("\r", "\\r").Replace("\n", "\\n")}|" +
                        $"{FFXIVMemory.GetStringFromBytes(value, Math.Min(valueByteCount, valueSize)).Replace("\r", "\\r").Replace("\n", "\\n")}";
                }
            }
        }

        public const uint LogFileLineID = 262;
        public const string logLineName = "RSVData";
        public const string MachinaPacketName = "RSVData";

        public LineRSV(TinyIoCContainer container)
            : base(container, LogFileLineID, logLineName, MachinaPacketName) { }
    }
}
```

**Comment by Akurosia** [comment]
ok i can try it out today, if it works i can also make a PR for it

**Comment by xiashtra** [comment]
Was this adequately resolved by #390?  If so, I think this issue can be closed.

**Comment by Akurosia** [comment]
Yeah forgot about it after collecting all the informations, Closed

**Comment by Souma-Sumire** [comment]
The CN server is now on patch 7.05, and I'm experiencing the same issue. 

Unfortunately, I don’t have any experience with C#, so I would be immensely grateful if an expert could kindly submit a PR tailored for the CN server.

**Comment by valarnin** [comment]
> The CN server is now on patch 7.05, and I'm experiencing the same issue.
> 
> Unfortunately, I don’t have any experience with C#, so I would be immensely grateful if an expert could kindly submit a PR tailored for the CN server.

Enable the FFXIV ACT Plugin's debug option to dump all network packets, and then zone into the 4th floor savage fight. That'll dump all of the network packets sent at zone-in, which will include the RSV data. Then you can send the log file in a DM to me and I'll take a look. (it will have IDs names in the raw network packet data)
