### ISSUE TITLE
GetCombatants cannot retrieve fields that are not in DefaultCombatantFields

### ISSUE THREAD

**Issue by xpdota** [OverlayPlugin/OverlayPlugin#39]
From https://github.com/ngld/OverlayPlugin/issues/267

It seems that rather than just being the default, anything not in DefaultCombatantFields is unavailable to GetCombatants (e.g. TargetID, CP and GP). Expected behavior would be for, as the name would imply, DefaultCombatantFields to be a default, but it seems to be acting as both a default and a whitelist (see MiniParseEventSource.cs:336).

**Comment by valarnin** [comment]
For clarification, since I wrote the original implementation, this setup was used to avoid having to pull all fields on every call, which can be very slow.

I think it may make more sense to do a one-time init of all fields the first time the handler is called or when the class is initialized instead.

**Comment by valarnin** [comment]
Here's an example of every possible field.

1. `NetworkBuffs` never has valid data, no matter what buffs have been applied. Note that in testing the diff in #33, that showed buff data present in actual game memory as expected.
2. CP and GP values for other players don't have valid data, only valid data for the current player's character.

```json
{
	"Address": {
		"value": 1866685248224
	},
	"BNpcID": 901,
	"BNpcNameID": 541,
	"CastBuffID": 0,
	"CastDurationCurrent": 0,
	"CastDurationMax": 0,
	"CastTargetID": 3758096384,
	"CurrentCP": 0,
	"CurrentGP": 0,
	"CurrentHP": 44,
	"CurrentMP": 0,
	"CurrentWorldID": 0,
	"EffectiveDistance": 42,
	"Heading": -2.43451262,
	"ID": 1073743825,
	"IsCasting": false,
	"Job": 0,
	"Level": 1,
	"MaxCP": 0,
	"MaxGP": 0,
	"MaxHP": 44,
	"MaxMP": 10000,
	"Name": "Striking Dummy",
	"NetworkBuffs": ["<omitted for brevity>"],
	"Order": 10,
	"OwnerID": 0,
	"PartyType": 0,
	"PosX": 253.5589,
	"PosY": -214.0755,
	"PosZ": 105.984283,
	"TargetID": 277187981,
	"WorldID": 0,
	"WorldName": "",
	"type": 2
}
```

(#33 buffs example)
```json
	"Effects": [
		{
			"BuffID": 364,
			"Stack": 30,
			"Timer": 30,
			"ActorID": 3758096384,
			"isOwner": false
		},
		{
			"BuffID": 365,
			"Stack": 10,
			"Timer": 30,
			"ActorID": 3758096384,
			"isOwner": false
		}
	],
```

**Comment by valarnin** [comment]
This issue is no longer relevant with the change to memory reading for `getCombatants`.
