### ISSUE TITLE
Cactbot P7S Purgation Stack/Spread callouts wrong after party member DC'd

### ISSUE THREAD

**Issue by valarnin** [OverlayPlugin/OverlayPlugin#60]
Basically the same issue as https://github.com/ngld/OverlayPlugin/issues/261, after a party member DCs and reconnects mid-instance the fired PartyChanged event is incomplete or otherwise incorrect in some manner, which causes cactbot's `isDPS` check in the `P7S Inviolate Purgation` trigger to come back with incorrect data.

**Comment by xpdota** [comment]
If I understand, it should be like this:
1. Party member DCs
2. OP sends incomplete info
3. Party member reconnects
4. OP sends complete info

But it's currently like this:
1. Party member DCs
2. OP sends incomplete info
3. Party member reconnects
4. Nothing

Is that what's happening? I'd think we'd still want step 2 to happen so that there's an indication that a player has disconnected.

**Comment by valarnin** [comment]
I haven't managed to catch this issue happening in-flight to be sure, but I think it's more like:
1. Party member DCs
2. OP sends complete info indicating party member has DC'd
3. Party member reconnects
4. OP sends incomplete info with party member who has reconnected missing some info

Theoretically based on the code in place, there should be a 5th event where OP should send another PartyChange with complete info, but I think that's not happening for some reason. See:
https://github.com/OverlayPlugin/OverlayPlugin/blob/936778302dc82cdb1619e8882bd1f03914342593/OverlayPlugin.Core/EventSources/MiniParseEventSource.cs#L475-L557

**Comment by quisquous** [comment]
I think in addition to this issue, the cactbot trigger should be made to be based on individual buffs and not based on roles.

**Comment by valarnin** [comment]
I've been using this locally to replace the trigger since it breaks pretty often for me. Not sure if it's 100% consistent either though. Also not really in a position to commit to cactbot at the moment.

```js
preRun: (data, matches) => {
  data.purgTracker ??= [undefined, undefined, undefined, undefined];
  data.purgCount ??= 0;
  ++data.purgCount;

  if (Conditions.targetIsYou()(data, matches)) {
    const effectId = matches.effectId.toUpperCase();
    const duration = parseFloat(matches.duration);
    if(duration < 11) {
      data.purgTracker[0] = effectIdToOutputStringKey[effectId];
    } else if(duration < 26) {
      data.purgTracker[1] = effectIdToOutputStringKey[effectId];
    } else if(duration < 41) {
      data.purgTracker[2] = effectIdToOutputStringKey[effectId];
    } else if(duration < 56) {
      data.purgTracker[3] = effectIdToOutputStringKey[effectId];
    } else {
      console.log(`Invalid purg debuff duration ${duration}`);
    }
  }
},
durationSeconds: 55,
infoText: (data, _matches, output) => {
  if (data.purgCount !== 20)
    return;

  Object.keys(data.purgTracker).forEach(k=>data.purgTracker[k]??='stack');

  const [effect1, effect2, effect3, effect4] = Object.values(data.purgTracker);

  // Store effects for reminders later
  data.purgationEffects = [effect1, effect2, effect3, effect4];

  return output.comboText({
    effect1: output[effect1](),
    effect2: output[effect2](),
    effect3: output[effect3](),
    effect4: output[effect4](),
  });
},
```
