### ISSUE TITLE
Make Opcode Updates Seamless for the End User

### ISSUE THREAD

**Issue by panicstevenson** [OverlayPlugin/OverlayPlugin#65]
Moving a discussion from #51.

Without repeating all of the notes from above, there might be a worthwhile enhancement to the OverlayPlugin release cycle around updating opcodes. Generally, opcode changes aren't engaging to the end user, thus create a mandatory, yet relatively low value, update prompt when the end user opens ACT or manually checks for new updates.

Because of this, there should be some mechanism that drives the necessary end user engagement down. It would also be worthwhile if this could drive the maintainer cost down as well, since creating a release is not automatic. There's various possible options to take here, but to name some at a high level that could work well with the given ecosystem:

- Check remote GitHub for changes to opcodes.json in the background
- Have GitHub actions cut a release and automatically push it when opcodes.json is updated
- Create an option for the end user to automatically consume updates

The first solves both sides of the issue, but is then potentially downloading something without the end user's consent, which, given the size, content, and mechanism, is probably okay. The other two both don't individually solve both parts of the issue and would require some additional component to address the spirit of this issue.

My personal take would be to opt for the last option presented above and then continue to work to remove pains from the maintainers' lifecycle since most people maintaining this project have other projects (in addition to their other commitments); however, that shouldn't be seen as a blocker since I believe effectively all of these options can be mixed and matched to come up with a workable solution.

**Comment by panicstevenson** [comment]
Replying to @xpdota from the other thread:

> Would having it automatically update when it sees that the game version is not found in the opcodes file work? I think the case that that doesn't handle is if someone gets the opcode wrong, pushes an update with it, but since that would be uncommon, you could just manually push a release with the fixed code.

I think this would work well enough as well; it provides an optimization that would make checking GitHub less necessary (probably not necessary from GitHub's end, but definitely being a better user of the platform). I don't exactly know how opcodes work well enough to know how they work across the various locales, but, from how they look at a surface-level, this sounds sufficient enough to approach bringing down the number of checks.

There's still an issue at the end of this where does OverlayPlugin simply use the values it found from GitHub or does it attempt to also write to disk (potentially overwriting opcodes.json or writing it somewhere as a temporary means until the next update)?  I think there's pros and cons to each approach, but I don't think that making network calls is a very strong con, but it would mean that the next OverlayPlugin release does have to come "eventually" so that the plugin sees that it has the available opcode. Inversely, if OverlayPlugin downloads the new opcodes.json, theoretically the plugin could continue to work for long periods of time without an official release. The downside there obviously being that any failed update will be much harder to troubleshoot.

**Comment by quisquous** [comment]
I think in my imagining of this, it would cache them somewhere (on disk, in OverlayPlugin config) so that it could permanently continue to work for long periods of time without a release.

I think if there is a continuous failed update for some reason, the log should already have `No opcodes for game version {version}` in it.  This should make it obvious enough when debugging as "what's in the log" is a pretty common question.  (I think a bunch of those should get upgraded to errors, but it should be ok as-is right now too.)

The idea of only checking when it can't be found makes a lot of sense to me and simplifies a lot of things.

**Comment by valarnin** [comment]
I think that to me it makes the most sense to check once on ACT start, and just follow the already existing `Automatically check for updates` checkbox on the `General` tab.
